import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import CSS from 'csstype';
import React from 'react';
import logo from './static/logo_light.gif';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Alice Bibaud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-white to-black/40">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight text-black sm:text-[5rem]">
            Alice Bibaud
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-black/10 p-4 text-black hover:bg-black/5"
              href="/resume.tsx" target="_blank"
            >
              <h3 className="text-2xl font-bold">Resume</h3>
              <div className="text-lg">
                I am an intellectually curious software engineer with experience in academic, industry, and research settings, interested in the social implications of data collection and network science.
              </div>
            </Link>
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-black/10 p-4 text-black hover:bg-black/5"
              href="https://principles-of-software.github.io/Principles-of-Software/#/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Principles of Software Textbook</h3>
              <div className="text-lg">
                I wrote a textbook for Principles of Software, the software design course RPI.
              </div>
            </Link>
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-black/10 p-4 text-black hover:bg-black/5"
              href="https://rcos.up.railway.app/handbook?semester=202301"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Rensselaer Center for Open Source (RCOS)</h3>
              <div className="text-lg">
                RCOS gives students the ability to work on personal coding projects for course credit.
              </div>
            </Link>
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-black/10 p-4 text-black hover:bg-black/5"
              href="https://github.com/alicebibaud"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">GitHub</h3>
              <div className="text-lg">
                I am very active in a number of open source communities.  Take a peak here.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
