import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import CSS from 'csstype';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Resume</title>
        <meta name="my resume" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#93c9a2] to-[#1c3d2f]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Resume
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://alicebibaud.github.io/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Website</h3>
              <div className="text-lg">
                A portfolio website that hopefully showcases some of my achievements.
              </div>
            </Link>
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://principles-of-software.github.io/Principles-of-Software/#/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Principles of Software Textbook</h3>
              <div className="text-lg">
                I wrote a textbook for Principles of Software, a course number CSCI 2600 at RPI.
              </div>
            </Link>
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://rcos.up.railway.app/handbook?semester=202301"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">RCOS</h3>
              <div className="text-lg">
                Rensselaer Center for Open Source (RCOS) has taken up all of my time and energy during my undergraduate career.
              </div>
            </Link>
            <Link
              className="flex max-w-s flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://github.com/alicebibaud"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">GitHub</h3>
              <div className="text-lg">
                Check out all of my public coding projects here.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
